# simple
# des
# default: 

CacheExcludeSize = 0x12
CacheExcludeAddr = 0x01
MinNumBytesFlashDL = 0
SkipProgOnCRCMatch = 1
VerifyDownload = 1
AllowCaching = 1
EnableFlashDL = 2
Override = 0
Device="ARM7"
